### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/restSE2pp#11]
- [x] https://github.com/vjcitn/restSE2pp/blob/7bd76a28afc45c300aa22c5abdea9bf3c243887f/supplem.tex#L142 no need for 'www'
- [x] https://github.com/vjcitn/restSE2pp/blob/7bd76a28afc45c300aa22c5abdea9bf3c243887f/supplem.tex#L160 if this is supposed to be in devel then there needs to be a `install(version = "devel")`
- [x] https://github.com/vjcitn/restSE2pp/blob/7bd76a28afc45c300aa22c5abdea9bf3c243887f/fig2supp.tex#L5 somehow I install this package without rhdf5client; shouldn't rhdf5client be a dependency of some sort?
- [x] https://github.com/vjcitn/restSE2pp/blob/7bd76a28afc45c300aa22c5abdea9bf3c243887f/fig2supp.tex#L11 I don't think as.numeric() is necessary here.
- [ ] https://github.com/vjcitn/restSE2pp/blob/7bd76a28afc45c300aa22c5abdea9bf3c243887f/supplem.tex#L295 this line formats poorly?

**Comment by vjcitn** [comment]
all comments valid and addressed.  we cannot use fixed width font and hyphenation together it seems -- without burning a few hours -- so we have some font usage irregularity in the supplement, but we do not bleed over margin any more
